# Generated by Django 4.0.2 on 2022-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=80)),
                ('date_of_birth', models.DateField(default=1995)),
                ('place_of_birth', models.CharField(max_length=255)),
            ],
        ),
    ]
